-- Coffee Finder — private research ledger.
--
-- Remembers candidates the editor's Brain already investigated and rejected,
-- so later discovery jobs do not spend time on the same generic or unsupported
-- café again. This is internal editorial evidence, never public map data.

create table if not exists public.research_ledger (
  id            bigint generated by default as identity primary key,
  name          text not null,
  name_key      text not null,
  comuna        text,
  comuna_key    text not null default '',
  status        text not null check (status in (
                  'generic', 'not_specialty', 'insufficient_evidence', 'closed'
                )),
  reason        text not null,
  sources       text[] not null default '{}',
  reviewed_at   timestamptz not null default now(),
  recheck_after timestamptz,
  created_by    text not null default coalesce(auth.jwt() ->> 'email', ''),
  updated_at    timestamptz not null default now(),
  unique (name_key, comuna_key)
);

create index if not exists research_ledger_active_idx
  on public.research_ledger (recheck_after, reviewed_at desc);

alter table public.research_ledger enable row level security;

-- Visitors never see editorial rejection notes. Only allowlisted editors can
-- read or change the ledger, using the same database-enforced check as places.
drop policy if exists "only editors read research ledger" on public.research_ledger;
create policy "only editors read research ledger"
  on public.research_ledger for select to authenticated
  using (public.is_editor());

drop policy if exists "only editors insert research ledger" on public.research_ledger;
create policy "only editors insert research ledger"
  on public.research_ledger for insert to authenticated
  with check (public.is_editor());

drop policy if exists "only editors update research ledger" on public.research_ledger;
create policy "only editors update research ledger"
  on public.research_ledger for update to authenticated
  using (public.is_editor()) with check (public.is_editor());

drop policy if exists "only editors delete research ledger" on public.research_ledger;
create policy "only editors delete research ledger"
  on public.research_ledger for delete to authenticated
  using (public.is_editor());

create or replace function public.touch_research_ledger()
returns trigger language plpgsql as $$
begin
  new.updated_at := now();
  new.created_by := coalesce(nullif(new.created_by, ''), auth.jwt() ->> 'email', '');
  return new;
end;
$$;

drop trigger if exists research_ledger_touch on public.research_ledger;
create trigger research_ledger_touch
  before insert or update on public.research_ledger
  for each row execute function public.touch_research_ledger();

comment on table public.research_ledger is
  'Private editor-only record of rejected café research, with evidence and recheck dates.';
